#ifndef LVRC_OPENGL_HPP
#define LVRC_OPENGL_HPP

#include <glad/glad.h>
#include <string>
#include <tuple>
#include <iostream>
#include <renderer/opengl/utils/Math.hpp>

/*!
 * Get the string corresponding to the given OpenGL error enum.
 * \param error An OpenGL error enum.
 * \return The string corresponding to the enum \p error.
 */
inline std::string glGetErrorString(GLenum error) {
    switch (error) {
    case GL_NO_ERROR:
        return "No error";
    case GL_INVALID_ENUM:
        return "Invalid enum";
    case GL_INVALID_VALUE:
        return "Invalid value";
    case GL_INVALID_OPERATION:
        return "Invalid operation";
    case GL_INVALID_FRAMEBUFFER_OPERATION:
        return "Invalid framebuffer operation";
    case GL_OUT_OF_MEMORY:
        return "Out of memory";
    case GL_STACK_UNDERFLOW:
        return "Stack underflow";
    case GL_STACK_OVERFLOW:
        return "Stack overflow";
    default:
        return "Unknown";
    }
}

/*!
 * Get all the previously generated OpenGL errors as a string separated by ', '.
 * \return A string containing all the errors generated by OpenGL.
 */
inline std::string glGetErrorsString() {
    GLenum error;
    std::string errors;
    while ((error = glGetError()) != GL_NO_ERROR) {
        if (!errors.empty()) {
            errors += ", ";
        }
        errors += glGetErrorString(error);
    }
    return errors;
}

/*!
 * Write to stdout a bunch of information concerning the current OpenGL
 * implementation.
 */
inline void printOpenGLInfo() {
    int values[3];
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 0, &values[0]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 1, &values[1]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 2, &values[2]);
    std::cout << "Max global workgroups           : "
              << values[0]
              << "x" << values[1]
              << "x" << values[2]
              << std::endl;

    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 0, &values[0]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 1, &values[1]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_SIZE, 2, &values[2]);
    std::cout << "Max local workgroup size        : "
              << values[0]
              << "x" << values[1]
              << "x" << values[2]
              << std::endl;

    glGetIntegerv(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS, &values[0]);
    std::cout << "Max local workgroup invocations : " << values[0]
              << std::endl;

    glGetIntegerv(GL_MAX_TEXTURE_BUFFER_SIZE, &values[0]);
    std::cout << "Max Texture Buffer Size         : "
              << formatSize(values[0])
              << std::endl;

    glGetIntegerv(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS, &values[0]);
    std::cout << "Max SSBO bindings               : "
              << values[0]
              << std::endl;

    glGetIntegerv(GL_MAX_SHADER_STORAGE_BLOCK_SIZE, &values[0]);
    std::cout << "Max SSBO size block             : "
              << formatSize(values[0])
              << std::endl;

    glGetIntegerv(GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS, &values[0]);
    std::cout << "Max compute shader blocks       : "
              << values[0]
              << std::endl;

    glGetIntegerv(GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS, &values[0]);
    std::cout << "Max combined SSBO               : "
              << values[0]
              << std::endl;
}

struct OpenGlDebugMessage {
    OpenGlDebugMessage(const GLenum source, const GLenum type,
                       const GLenum severity, const GLuint id,
                       const std::string& message) :
            source(source), type(type), severity(severity),
            id(id), message(message),
            logEntry() {
        switch (source) {
        case GL_DEBUG_SOURCE_API:
            logEntry += "[OpenGL API]";
            break;
        case GL_DEBUG_SOURCE_WINDOW_SYSTEM:
            logEntry += "[Window System]";
            break;
        case GL_DEBUG_SOURCE_SHADER_COMPILER:
            logEntry += "[Shader Compiler]";
            break;
        case GL_DEBUG_SOURCE_THIRD_PARTY:
            logEntry += "[Third Party]";
            break;
        case GL_DEBUG_SOURCE_APPLICATION:
            logEntry += "[Application]";
            break;
        default:
            logEntry += "[Other]";
            break;
        }

        switch (severity) {
        case GL_DEBUG_SEVERITY_HIGH:
            logEntry += "[HIGH  ]";
            break;
        case GL_DEBUG_SEVERITY_MEDIUM:
            logEntry += "[MEDIUM]";
            break;
        case GL_DEBUG_SEVERITY_LOW:
            logEntry += "[LOW   ]";
            break;
        case GL_DEBUG_SEVERITY_NOTIFICATION:
            logEntry += "[NOTIF ]";
            break;
        default:
            logEntry += "[ ???? ]";
            break;
        }

        logEntry += "(" + std::to_string(id) + ")";

        switch (type) {
        case GL_DEBUG_TYPE_ERROR:
            logEntry += "Error: ";
            break;
        case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR:
            logEntry += "Deprecated behavior: ";
            break;
        case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:
            logEntry += "Undefined behavior: ";
            break;
        case GL_DEBUG_TYPE_PORTABILITY:
            logEntry += "Portability: ";
            break;
        case GL_DEBUG_TYPE_PERFORMANCE:
            logEntry += "Performance: ";
            break;
        default:
            logEntry += " ";
            break;
        }

        logEntry += message;
    }

    const GLenum source;
    const GLenum type;
    const GLenum severity;
    const GLuint id;
    const std::string message;

    std::string logEntry;

    friend bool operator==(const OpenGlDebugMessage& left,
                           const OpenGlDebugMessage& right) {
        return left.source == right.source
            && left.type == right.type
            && left.severity == right.severity
            && left.id == right.id
            && left.message == right.message;
    }

    friend bool operator!=(const OpenGlDebugMessage& left,
                           const OpenGlDebugMessage& right) {
        return !operator==(left, right);
    }

    [[nodiscard]] const std::string& toString() const {
        return logEntry;
    }

    [[nodiscard]] std::tuple<float, float, float, float> getDisplayColor() const {
        switch (severity) {
        case GL_DEBUG_SEVERITY_HIGH:
            return std::make_tuple(1.0f, 0.0f, 0.0f, 1.0f);
        case GL_DEBUG_SEVERITY_MEDIUM:
            return std::make_tuple(1.0f, 0.2f, 0.0f, 1.0f);
        case GL_DEBUG_SEVERITY_LOW:
            return std::make_tuple(1.0f, 1.0f, 0.0f, 1.0f);
        case GL_DEBUG_SEVERITY_NOTIFICATION:
            return std::make_tuple(0.12f, 0.56f, 1.0f, 1.0f);
        default:
            return std::make_tuple(1.0f, 1.0f, 1.0f, 1.0f);
        }
    }
};

#endif //LVRC_OPENGL_HPP
